//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySave.View.Ressources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySave.View.Ressources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current business software(s) which stop.
        /// </summary>
        public static string BS1 {
            get {
                return ResourceManager.GetString("BS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SaveWork(s) at their launch.
        /// </summary>
        public static string BS2 {
            get {
                return ResourceManager.GetString("BS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New software.
        /// </summary>
        public static string BS3 {
            get {
                return ResourceManager.GetString("BS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new business software.
        /// </summary>
        public static string BS4 {
            get {
                return ResourceManager.GetString("BS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete business software(s) selected.
        /// </summary>
        public static string BS5 {
            get {
                return ResourceManager.GetString("BS5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose an appellation.
        /// </summary>
        public static string CBV1 {
            get {
                return ResourceManager.GetString("CBV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a source directory.
        /// </summary>
        public static string CBV2 {
            get {
                return ResourceManager.GetString("CBV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a target directory.
        /// </summary>
        public static string CBV3 {
            get {
                return ResourceManager.GetString("CBV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a type.
        /// </summary>
        public static string CBV4 {
            get {
                return ResourceManager.GetString("CBV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create backup.
        /// </summary>
        public static string CBV5 {
            get {
                return ResourceManager.GetString("CBV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which backup do you want to delete?.
        /// </summary>
        public static string DBV1 {
            get {
                return ResourceManager.GetString("DBV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have the choice between:.
        /// </summary>
        public static string DBV2 {
            get {
                return ResourceManager.GetString("DBV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete backup(s) chosen.
        /// </summary>
        public static string DBV3 {
            get {
                return ResourceManager.GetString("DBV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restore backup.
        /// </summary>
        public static string Decrypt {
            get {
                return ResourceManager.GetString("Decrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which backup do you want to execute?.
        /// </summary>
        public static string EBV1 {
            get {
                return ResourceManager.GetString("EBV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have the choice between:.
        /// </summary>
        public static string EBV2 {
            get {
                return ResourceManager.GetString("EBV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute backup(s) chosen.
        /// </summary>
        public static string EBV3 {
            get {
                return ResourceManager.GetString("EBV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current extension(s) for files to encrypt.
        /// </summary>
        public static string EKV1 {
            get {
                return ResourceManager.GetString("EKV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New.
        /// </summary>
        public static string EKV2 {
            get {
                return ResourceManager.GetString("EKV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a new extension.
        /// </summary>
        public static string EKV3 {
            get {
                return ResourceManager.GetString("EKV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete extension(s) selected.
        /// </summary>
        public static string EKV4 {
            get {
                return ResourceManager.GetString("EKV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current key for Encryption:.
        /// </summary>
        public static string EV1 {
            get {
                return ResourceManager.GetString("EV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New key for Encryption:.
        /// </summary>
        public static string EV2 {
            get {
                return ResourceManager.GetString("EV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Generate new key.
        /// </summary>
        public static string EV3 {
            get {
                return ResourceManager.GetString("EV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change the key.
        /// </summary>
        public static string EV4 {
            get {
                return ResourceManager.GetString("EV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to EasySave.
        /// </summary>
        public static string HV1 {
            get {
                return ResourceManager.GetString("HV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The current log extention is:.
        /// </summary>
        public static string LE1 {
            get {
                return ResourceManager.GetString("LE1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the new log extention desired.
        /// </summary>
        public static string LE2 {
            get {
                return ResourceManager.GetString("LE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change log extension.
        /// </summary>
        public static string LE3 {
            get {
                return ResourceManager.GetString("LE3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The existing path for the log file is:.
        /// </summary>
        public static string LFP1 {
            get {
                return ResourceManager.GetString("LFP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the new desired path:.
        /// </summary>
        public static string LFP2 {
            get {
                return ResourceManager.GetString("LFP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change path.
        /// </summary>
        public static string LFP3 {
            get {
                return ResourceManager.GetString("LFP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What do you want to do?.
        /// </summary>
        public static string MB1 {
            get {
                return ResourceManager.GetString("MB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Execute backup.
        /// </summary>
        public static string MB2 {
            get {
                return ResourceManager.GetString("MB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create backup.
        /// </summary>
        public static string MB3 {
            get {
                return ResourceManager.GetString("MB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify backup.
        /// </summary>
        public static string MB4 {
            get {
                return ResourceManager.GetString("MB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete backup.
        /// </summary>
        public static string MB5 {
            get {
                return ResourceManager.GetString("MB5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which backup do you want to modify?.
        /// </summary>
        public static string MBV1 {
            get {
                return ResourceManager.GetString("MBV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have the choice between:.
        /// </summary>
        public static string MBV2 {
            get {
                return ResourceManager.GetString("MBV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify backup.
        /// </summary>
        public static string MBV3 {
            get {
                return ResourceManager.GetString("MBV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption key.
        /// </summary>
        public static string MEV1 {
            get {
                return ResourceManager.GetString("MEV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add file extension to encrypt.
        /// </summary>
        public static string MEV2 {
            get {
                return ResourceManager.GetString("MEV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Which path do you want to change?.
        /// </summary>
        public static string MPV1 {
            get {
                return ResourceManager.GetString("MPV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The log file path.
        /// </summary>
        public static string MPV2 {
            get {
                return ResourceManager.GetString("MPV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The state file path.
        /// </summary>
        public static string MPV3 {
            get {
                return ResourceManager.GetString("MPV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The save file path.
        /// </summary>
        public static string MPV4 {
            get {
                return ResourceManager.GetString("MPV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string MW1 {
            get {
                return ResourceManager.GetString("MW1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SaveWorks.
        /// </summary>
        public static string MW2 {
            get {
                return ResourceManager.GetString("MW2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SaveWorks.
        /// </summary>
        public static string MW3 {
            get {
                return ResourceManager.GetString("MW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings.
        /// </summary>
        public static string MW4 {
            get {
                return ResourceManager.GetString("MW4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High-priority files&apos;s types.
        /// </summary>
        public static string PF1 {
            get {
                return ResourceManager.GetString("PF1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a type.
        /// </summary>
        public static string PF2 {
            get {
                return ResourceManager.GetString("PF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete a type.
        /// </summary>
        public static string PF3 {
            get {
                return ResourceManager.GetString("PF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Return.
        /// </summary>
        public static string ReturnButton {
            get {
                return ResourceManager.GetString("ReturnButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a language.
        /// </summary>
        public static string SAL {
            get {
                return ResourceManager.GetString("SAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The existing path for the save file is:.
        /// </summary>
        public static string SFP1 {
            get {
                return ResourceManager.GetString("SFP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the new desired path:.
        /// </summary>
        public static string SFP2 {
            get {
                return ResourceManager.GetString("SFP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change path.
        /// </summary>
        public static string SFP3 {
            get {
                return ResourceManager.GetString("SFP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shortcuts.
        /// </summary>
        public static string shortcuts {
            get {
                return ResourceManager.GetString("shortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The existing path for the state file is:.
        /// </summary>
        public static string STFP1 {
            get {
                return ResourceManager.GetString("STFP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the new desired path:.
        /// </summary>
        public static string STFP2 {
            get {
                return ResourceManager.GetString("STFP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change path.
        /// </summary>
        public static string STFP3 {
            get {
                return ResourceManager.GetString("STFP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à What do you want to do?.
        /// </summary>
        public static string SV1 {
            get {
                return ResourceManager.GetString("SV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encryption.
        /// </summary>
        public static string SV2 {
            get {
                return ResourceManager.GetString("SV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files path.
        /// </summary>
        public static string SV3 {
            get {
                return ResourceManager.GetString("SV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log extension.
        /// </summary>
        public static string SV4 {
            get {
                return ResourceManager.GetString("SV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Business software.
        /// </summary>
        public static string SV5 {
            get {
                return ResourceManager.GetString("SV5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string SV6 {
            get {
                return ResourceManager.GetString("SV6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à High-priority files.
        /// </summary>
        public static string SV7 {
            get {
                return ResourceManager.GetString("SV7", resourceCulture);
            }
        }
    }
}
